spring:
    datasource:
        password: 123ma321
        url: jdbc:postgresql://localhost:5432/jwt_security
        username: abd
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
